update inline documentation
CodeForAfricaLabs/starhealth pull request #21
Opened 2017-09-12 15:04 UTC by andela-johia

#### What does this PR do?
- This PR updates the documentation for the javascript and HTML files

#### Description of task completed?
- Write JSDOC for javascript functions to capture their use cases
- Write inline comments for HTML files

2017-09-13 11:28 UTC, DavidLemayian requested changes
@andela-johia Thanks for sending this.

Starting with sentence case, let's ensure we're keeping titles and descriptions (in comment and PR) clean by starting with uppercase letters and using periods at the end of sentences where appropriate.

Also, for the comments added, we should make sure we aren't adding comments just for the sake of it.

We should also ensure that if someone who doesn't know anything about the project is able to understand the reason for the comment and what the function / HTML's purpose is.

2017-09-13 11:50 UTC, andela-johia commented
@DavidLemayian Thanks for the feedback.
Could you shed more light on where the comments in the HTML or Javascript files need refactoring.

2017-09-13 11:51 UTC, DavidLemayian commented
@andela-johia Some reading:

1. https://google.github.io/styleguide/jsguide.html#jsdoc
2. https://github.com/airbnb/javascript#comments
3. https://github.com/hail2u/html-best-practices

2017-09-20 15:31 UTC, DavidLemayian approved these changes

2017-09-20 15:32 UTC, merged