Added nhif & health facilities queries
CodeForAfricaLabs/starhealth pull request #5
Opened 2017-02-14 07:08 UTC by samoei

This update branch includes the nhif and health facilities queries to the lambda function.

Also notice i have removed all the functions which were not being used.

2017-02-14 09:56 UTC, DavidLemayian requested changes
@samoei I've left a couple of changes that need to happen before accepting the merge.

2017-02-14 09:56 UTC, DavidLemayian commented on lambda_function.py
> +        msg_items.append("Example query for health facility: HF KITALE")
Let's make it:
```python
msg_items.append("Example query for health facility: Hosp. KITALE")
```

Let's actually change the entire response as:

>We could not understand your query. Try these:
>1. Doctors: DR. SAMUEL AMAI
>2. Clinical Officers: CO SAMUEL AMAI
>3. Nurses: NURSE SAMUEL AMAI
>4. NHIF accredited hospital: NHIF KITALE
>5. Health Facility: HF KITALE

2017-02-14 09:56 UTC, DavidLemayian commented on lambda_function.py
> +        msg_items.append("Example query for health facility: HF KITALE")
@samoei ☝️

2017-02-14 09:56 UTC, DavidLemayian commented on lambda_function.py
> +        return "Could not find a nurse with that name"
Let's fix up not being able to find this.

2017-02-14 09:56 UTC, DavidLemayian commented on lambda_function.py
> +        return "Could not find a nurse with that name"
Message:
> The location you provided is currently not served by an NHIF accredited hospital.

2017-02-14 09:56 UTC, DavidLemayian commented on lambda_function.py
> +        return "Could not find a nurse with that name"
Fix on the response message here as well.

2017-02-14 11:58 UTC, DavidLemayian requested changes
@samoei Just a small fix.

2017-02-14 11:58 UTC, DavidLemayian commented on lambda_function.py
> +        return "The location you provided is currently not served by an NHIF accredited hospital."
Let's change this to:
```python
return "We could not find an NHIF accredited hospital in the location you provided."
```

2017-02-14 12:08 UTC, samoei commented on lambda_function.py
> +        return "The location you provided is currently not served by an NHIF accredited hospital."
@DavidLemayian I have updated this

2017-02-15 03:57 UTC, DavidLemayian approved these changes

2017-02-15 03:57 UTC, merged